### ISSUE TITLE
clean up .h pollution

### ISSUE THREAD

**Issue by tjhance** [shewu/h4ck4th0n#48]
Right now lots of .cpp files are indirectly including .h files that they don't need, which is now a problem since cleaning this up can speed of compilation.

**Comment by shewu** [comment]
looks like there's `clang -MM` to get a list of includes for a cpp file.

**Comment by shewu** [comment]
oh, that's what `clang -MF` does, but writes to a file. from what I can tell by looking at the .d files, they seem to be including the minimum number of includes, so we can close this.
