### ISSUE TITLE
Set up clang-format to automate formatting

### ISSUE THREAD

**Issue by shewu** [shewu/h4ck4th0n#51]
clang-format should use the google c++ style guide. in particular, the biggest impact clang-format will bring is moving from a combination of spaces and tabs to ~~2-space~~ 4-space indentation.

**Comment by tjhance** [comment]
do we _have_ to use 2 space tabs just because google does?

**Comment by shewu** [comment]
4 is fine, just not 8. 8 introduces too much whitespace. i like 4 because statements in a for loop begin under the parens, among other (legacy) reasons.

**Comment by tjhance** [comment]
yeah I don't like 8 either. I used to use 8, wayy back in the day, but I'm mostly accustomed to 4. I _can_ do 2 (actually, the codebase at my work uses 2) but I still prefer 4.

**Comment by shewu** [comment]
https://github.com/shewu/h4ck4th0n/commit/428dbf01f9e455e04818e368b37b16fdac990fe4
