### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by vladfi1** [shewu/h4ck4th0n#53]
The following directories are missing:

* bin/deps/src
* bin/objs

They could (should) be created by the makefile.

**Comment by vladfi1** [comment]
Apparently logs is also missing, causing the server to abort.

**Comment by shewu** [comment]
To https://github.com/shewu/h4ck4th0n
   52ca1e7..caa6add  master -> master

speculative fix in caa6add. @tjhance can you verify that make compiles without issues if those directories don't already exist?

**Comment by shewu** [comment]
this should work now https://github.com/shewu/h4ck4th0n/commit/bfc6a6c4c406658f63b3df61748713dc4036e658
